### ISSUE TITLE
Affichage étrange de certaines lignes

### ISSUE THREAD

**Issue by thomasschmit** [Cqoicebordel/travel-time-metro-d3#13]
![Extrait du plan centré sur la gare de Tournan](https://cloud.githubusercontent.com/assets/6014433/6432620/cb1eede8-c057-11e4-95b5-369515dc39b2.png)

Certaines lignes s'affichent bizarrement, là. Notamment la T1. L'algorithme ne peut-il pas trouver une meilleure disposition des points ?

**Comment by Cqoicebordel** [comment]
Hum... Honnêtement, je ne comprend pas ce que tu veux dire...

Les points sont placés suivant deux caractéristiques : le temps vers le centre, et l'angle (l'azimuth) avec pour centre la station choisie. En gros, des coordonnées polaires.  
Donc les positions sont loin d'être aléatoire.

Pour moi il y a un soucis vis à vis de la superposition, mais pour le reste, je vois pas trop comment gérer, et surtout, par quelle solution remplacer le choix actuel.

**Comment by thomasschmit** [comment]
Ouais, tu as raison. L’affichage me semblait étrange, mais en y réfléchissant bien, tout est normal.
