### ISSUE TITLE
Ajouter les lignes de RER et de tramway

### ISSUE THREAD

**Issue by thomasschmit** [Cqoicebordel/travel-time-metro-d3#2]
Ça ne devrait pas être bien difficile et ça rendrait le plan plus complet :)

**Comment by Cqoicebordel** [comment]
Mais aussi plus chargé...

Le problème également, c'est qu'il n'y a pas encore d'outils de navigation, donc pas de zoom. Et avec la longueur des lignes de RER, le metro sera tout petit au milieu.

**Comment by thomasschmit** [comment]
Ah oui, bonne remarque !

**Comment by Cqoicebordel** [comment]
Bon, normalement toutes les lignes Métro, Tram et RER ont été faites.

Reste les bus et les transiliens ;)  
Mais ça, on verra plus tard, quand j'aurais trouvé un moyen d'automatiser le truc...

**Comment by thomasschmit** [comment]
Bravo !

Je ne suis pas sûr qu’il faille intégrer les lignes de bus et de Transilien. Ça rendrait la carte vraiment illisible. Par contre, on peut rajouter les stations de RER dans Paris au plan de métro, non ?

**Comment by Cqoicebordel** [comment]
Pourquoi pas, même si je suis pas un grand fan de l'idée.  
C'est l'idée de couper des lignes en plein milieu qui me gène, mais on verra.

Pour le bus et le transilien, d'autres cartes pourraient être faites, comme le rail national après.

De toute façon, y'a encore plein de bugs à résoudre avant d'en arriver là. J'aimerais d'abord les résoudre, puis faire un peu de pub pour ce machin, et espérer un peu d'aide pour la suite ;)

**Comment by thomasschmit** [comment]
Ah oui, je comprends. Pourtant, c’est ce que fait la RATP sur son plan. Elle ajoute même quelques unes des lignes de tramway et de Transilien.

Dans les jours avenir, je vais essayer de te filer un coup de main sur la partie JavaScript. Je ne maîtrise pas bien le langage, mais ce sera l’occasion d’apprendre.

À terme, on peut imaginer que la carte trouve sa place sur Raildar.fr. Ça la mettrait plus en avant :)

**Comment by Cqoicebordel** [comment]
Ouais, la RATP fait un peu n'importe quoi ;)

Pour Raildar, c'est pas forcément le but, mais ça ferait tout de même plaisir :)

J'suis pas non plus un grand spécialiste de JS, mais bon, une fois qu'on connait un langage, on les connait un peu tous...  
Et puis, tu m'as déjà filé de beaux coup de mains !!!

**Comment by Cqoicebordel** [comment]
Bon, je ferme ce bug, puisque c'est fait.

Mais c'est pas pour ça qu'on ne peut pas créer d'autres cartes avec plus de données...
